### ISSUE TITLE
Large pictures directories copy from Nexus 5 to PC fails: `AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10`

### ISSUE THREAD

**Issue by Niluge-KiWi** [hanwen/go-mtpfs#101]
Scenario:
* install go-mtpfs current master on archlinux (using AUR go-mtpfs)
* unlock the phone (Nexus 5, Android 5.1.1)
* plug the phone on usb
* mount mtp
* copy 2 large directories (~1500 jpg files)

Result:
Copy fails at some point, with error `AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10`

It's reproductible: I tried 4 times and it always failed. It seems to fail on the same files.

Trace:
```
$ fusermount -u ~/nexus-5-mtp
$ go-mtpfs ~/nexus-5-mtp/
2015/08/05 20:52:52 OpenSession failed: LIBUSB_ERROR_IO; attempting reset
2015/08/05 20:52:53 Configure failed: OpenSession after reset: LIBUSB_ERROR_IO
$ go-mtpfs ~/nexus-5-mtp/
2015/08/05 20:52:56 OpenSession failed: LIBUSB_ERROR_IO; attempting reset
2015/08/05 20:52:57 FUSE mounted
2015/08/05 20:55:08 AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10
2015/08/05 20:55:08 AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10
2015/08/05 20:55:08 AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10
2015/08/05 20:55:08 AndroidGetPartialObject64 failed: header specified 0x4 bytes, but have 0x10
```

**Comment by hanwen** [comment]
can you figure out which file is the one causing the error?

can you try changing line 250 of mtp/mtp.go from

  if restLen != len(rest) {

to

   if restLen > len(rest)

and see if that helps?

**Comment by luizbranco** [comment]
@hanwen I had the same issue as the OP, changing the ``if`` has fixed the copy.
