### ISSUE TITLE
rmdir removes non-empty directories

### ISSUE THREAD

**Issue by uafr** [hanwen/go-mtpfs#103]
Usually rmdir removes only empty folders. On go-mtpfs non-empty directories are deleted, too. Happens with version built last year as well as with latest version created by 'go get github.com/hanwen/go-mtpfs' today. 
No message aside form 'FUSE mounted' in the terminal running  go-mtpfs.

Device: Nexus 5, Android 5.1.1
PC: x86_64, Debian 8.0

**Comment by mnalis** [comment]
This silent data loss issue is still present in Debian Stretch 9.11 (go-mtpfs 0.0~git20150917.0.bc7c0)

**Comment by hanwen** [comment]
confirmed; file seems to be gone on remount too.

**Comment by hanwen** [comment]
I had assumed the VFS layer forbids this, but it happily forwards the request to FUSE.
