### ISSUE TITLE
Timeout, then it no longer works on that directory.

### ISSUE THREAD

**Issue by hookenz** [hanwen/go-mtpfs#105]
I guess it needs some tweaking!

```
root@slave:~/samsung/Card/DCIM/Camera# ls -l
2015/09/04 11:46:53 fatal error LIBUSB_ERROR_TIMEOUT; closing connection.
2015/09/04 11:46:58 GetObjectHandles failed: LIBUSB_ERROR_TIMEOUT
ls: cannot open directory .: Input/output error
```

**Comment by hanwen** [comment]
Is the directory very large? You can set the timeout over the command line with --usb-timeout.

**Comment by hookenz** [comment]
Yes, around 8000 files.  Thanks for the feedback.  Unfortunately I'm unlikely to try this again.  I came to the conclusion that MTP is terrible.  Perhaps worse than UMS which google they moved away from.

It's a shame that Google hasn't provided the facility to reboot phones into UMS mode with all the app's disabled (like single user)  So that way you could at least access your phone with some speed.  I don't care about using my phone when its in that mode.  I just wanted to get the files off it.  It has proven almost impossible to do so without an OTG cable.

So in the end I found the OTG cable option with an external flash drive or HDD to be the least painless method.

**Comment by hanwen** [comment]
FWIW, you can also use ADB in debug mode to transfer files. Good luck!
