### ISSUE TITLE
Unexpected writes to /tmp during an rsync

### ISSUE THREAD

**Issue by asayanna** [hanwen/go-mtpfs#109]
Hi Han-wen,
I'm seeing writes taking place to /tmp when using rsync to backup my phone DCIM data (Samsung Galaxy S4). The following is an example directory... 'go-mtpfs2388178'. The files in there are as zero bytes, however they are consuming significant space on /tmp. 
Wondering whether this is expected. 
Regards,
Alvin.

**Comment by hanwen** [comment]
yes. Unless you use the android extensions, the files are first created on the local disk before they are available through FUSE.

**Comment by asayanna** [comment]
Think I'm doing something wrong as I ran it without the -android flag the first time around, assuming it would default to true. I now hard set this and re-ran with the same outcome - /tmp filled up quickly. 
Here's my command line... 
"go-mtpfs -dev=04e8:6860 -android=true -usb-timeout=30000 -allow-other=true /media/SAMSUNG_Android"

I've re-run it with fs,usb,mtp debugging. Let me know if there's anything in there you'd like me to share. 

Regards,
Alvin

**Comment by hanwen** [comment]
it is likely that the Samsung phone does not support the android extensions.

if space on /tmp is a concern, you can set TMPDIR env var to point to another directory.
