### ISSUE TITLE
How to copy files to Android without using of /tmp 

### ISSUE THREAD

**Issue by DeedleMan** [hanwen/go-mtpfs#113]
Hi,

I'm trying to download a file using Transmission torrent client and store it to my Android phone (sandisk 64GB) directly BUT I get a message that there is not enough free space in local /tmp dir.

Pleaes advice how I can do it WITHOUT using local /tmp directory? I have no possiblity to extend it!

I've tried to set TMP/TEMP/TMPDIR environment vars to tmp folder created on android device but with no success.

**Comment by hanwen** [comment]
I can add a -tempdir option, but it should just work to set TMPDIR, ie.

  TMPDIR=/usr/local/tmp go-mtpfs /my/mount/point

**Comment by DeedleMan** [comment]
$ TMPDIR=/media/MyAndroid/Card/tmp go-mtpfs /media/MyAndroid
2016/01/31 23:46:10 compiled against libmtp 1.1.5
Device 0 (VID=04e8 and PID=6860) is a Samsung Galaxy models (MTP).
2016/01/31 23:46:10 found device Samsung: Galaxy models (MTP) (04e8:6860) @ bus 2, dev 4
: 
2016/01/31 23:46:10 storage ID 65537: Phone
2016/01/31 23:46:10 storage ID 131074: Card
2016/01/31 23:46:10 TempDir failed: mkdir /media/MyAndroid/Card/tmp/go-mtpfs073805401: no such file or directory

**Comment by hanwen** [comment]
TMPDIR should be a directory on your linux machine.

**Comment by DeedleMan** [comment]
Omg... so, no workarounds to copy a file directly to Android without using of tmp directory on my Linux?

**Comment by slump64** [comment]
I think the most reasonable thing is to blame Google that they use MTP in the first place, I'm sure there would be more sane and working solutions if not this Microsoft disaster.

**Comment by hanwen** [comment]
The original android MTP stack has Android extensions which allow in-place reads and writes of files. Some vendors (notably samsung and sony) have chosen to ship their own MTP stacks, so we have to stage files before sending, and this happens in a temp dir.

If you don't have enough space, you could select subranges of the file with dd, transfer those individually, and then concatenate when you transport data off the phone again.
