### ISSUE TITLE
Add ssl/https to http://hanwen.home.xs4all.nl/public/software/go-mtpfs/ (and also hashes)

### ISSUE THREAD

**Issue by OriginalPenguin** [hanwen/go-mtpfs#114]
Now that SSL is free with Let's Encrypt can you add it so it's less scary downloading binaries?

Also can you publish hashes (sha256 will be fine, or whatever algorithm you prefer) for all the binaries so we know they haven't tampered with?

Thanks!

**Comment by hanwen** [comment]
I changed the link to be HTTPS.
