### ISSUE TITLE
Uploading specific file to phone causes strange disconnect

### ISSUE THREAD

**Issue by Iiridayn** [hanwen/go-mtpfs#116]
File is the mp3 downloadable from https://soundcloud.com/ccpgames/eve-online-nouvelle-rouvenor - has sha1sum 844c1f5239ec1a730e862473235b37891143c69c  Nouvelle Rouvenor Hero.mp3.

Error log:

2016/04/03 11:20:09 fatal error LIBUSB_ERROR_TIMEOUT; closing connection.
2016/04/03 11:20:09 AndroidSendPartialObject failed: LIBUSB_ERROR_TIMEOUT
2016/04/03 11:20:09 AndroidSendPartialObject failed: mtp: cannot run operation ANDROID_SEND_PARTIAL_OBJECT, device is not open
2016/04/03 11:20:09 6194944 bytes in 26.403029081s: 0 mb/s
2016/04/03 11:20:09 AndroidEndEditObject failed: mtp: cannot run operation ANDROID_END_EDIT_OBJECT, device is not open
2016/04/03 11:20:27 GetStorageInfo 10001: mtp: cannot run operation GetStorageInfo, device is not open
2016/04/03 11:20:37 GetObjectHandles failed: mtp: cannot run operation GetObjectHandles, device is not open
2016/04/03 11:20:40 GetStorageInfo 10001: mtp: cannot run operation GetStorageInfo, device is not open

This happened immediately after transferring the file to the device. Device is a OnePlus One, system is Arch Linux, up to date. Have reproduced it three times, finally tracked down the file at fault.

**Comment by hanwen** [comment]
sounds like something on the phone crashed? How do I download this MP3? If you download the MP3 to your phone using the internet, does the file play correctly and appear in your music player?

**Comment by Iiridayn** [comment]
You can download the mp3 by clicking on the download link - last button I
think it was? I'll attach an image with the relevant button circled next
time I have since time at my computer.

The file does play correctly on both computer and phone, and the sha1sum is
the same on the phone, indicating successful transfer (verified by shelling
in via adb).

**Comment by hanwen** [comment]
i tried this here with my nexus 5x, but the file transfers without any problem.  I'm sorry, I don't what's wrong with your phone. You coudl try disabling android extensions.

**Comment by hanwen** [comment]
can't repro. This looks like a problem with your phone.o
