### ISSUE TITLE
File transfer file with android TWRP recovery.

### ISSUE THREAD

**Issue by edward81** [hanwen/go-mtpfs#118]
When i try to transfer file on TWRP recovery with go-mtpfs-git i get timeout error.

2016/06/04 10:54:54 fatal error LIBUSB_ERROR_TIMEOUT; closing connection.
2016/06/04 10:54:59 AndroidSendPartialObject failed: LIBUSB_ERROR_TIMEOUT
2016/06/04 10:54:59 AndroidSendPartialObject failed: mtp: cannot run operation ANDROID_SEND_PARTIAL_OBJECT, device is not open
2016/06/04 10:54:59 GetStorageInfo 10001: mtp: cannot run operation GetStorageInfo, device is not open
2016/06/04 10:54:59 GetStorageInfo 10001: mtp: cannot run operation GetStorageInfo, device is not open
2016/06/04 10:54:59 GetStorageInfo 10001: mtp: cannot run operation GetStorageInfo, device is not open

I get the same result with or without the switch "-android=true". I don't know if this is a go-mtpfs or TWRP implementation error. But the transfers is working fine with jmtpfs.

**Comment by hanwen** [comment]
Try -android=false

Op za 4 jun. 2016 12:10 schreef Bogar Boris <notifications@github.com>:

**Comment by edward81** [comment]
Working with android=false. My mistake, i don't read the help and I thought that the default is False.
Thanks.
