### ISSUE TITLE
 Failed to install go-mtpfs 

### ISSUE THREAD

**Issue by ekke107** [hanwen/go-mtpfs#128]
After the input of 'go get github.com/hanwen/go-mtpfs' the file gomtpfs does not exist on my system (Ubuntu 14.04 LTS)
Instead I get the output

ekkehard@EKKE:~$ go get github.com/hanwen/go-mtpfs
# golang.org/x/sys/unix
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:40: Pipe redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux_amd64.go:97
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:54: (*SockaddrInet4).sockaddr redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:363
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:68: (*SockaddrInet6).sockaddr redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:377
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:83: (*SockaddrUnix).sockaddr redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:392
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:109: Getsockname redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:776
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:120: GetsockoptString redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:842
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:130: ImplementsGetwd redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:232
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:134: Getwd redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:236
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:155: Getgroups redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:249
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:180: Setgroups redeclared in this block
	previous declaration at /tmp/go/src/golang.org/x/sys/unix/syscall_linux.go:275
/tmp/go/src/golang.org/x/sys/unix/syscall_solaris.go:180: too many errors

**Comment by hanwen** [comment]
what does go version say?

**Comment by hanwen** [comment]
(I think your go version is too old and does not recognize solaris as an operating system.)

**Comment by ekke107** [comment]
go version go1.2.1 linux/amd64

**Comment by hanwen** [comment]
you need go 1.4 or newer. see https://golang.org/dl/
