### ISSUE TITLE
fatal error LIBUSB_ERROR_OVERFLOW; closing connection.

### ISSUE THREAD

**Issue by likewhoa** [hanwen/go-mtpfs#130]
2018/08/07 07:00:49 MTP data 0x9e bytes
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 3e00 0000            ....... >...
2018/08/07 07:00:49 MTP response OK []
2018/08/07 07:00:49 MTP decoded &mtp.ObjectInfo{StorageID:0x10001, ObjectFormat:0x3000, ProtectionStatus:0x0, CompressedSize:0x8f05c29e, ThumbFormat:0x0, ThumbCompressedSize:0x0, ThumbPixWidth:0x0, ThumbPixHeight:0x0, ImagePixWidth:0x0, ImagePixHeight:0x0, ImageBitDepth:0x0, ParentObject:0x0, AssociationType:0x0, AssociationDesc:0x0, SequenceNumber:0x0, Filename:"WhatsApp.zip", CaptureDate:time.Time{wall:0x0, ext:63669233472, loc:(*time.Location)(nil)}, ModificationDate:time.Time{wall:0x0, ext:62135578799, loc:(*time.Location)(nil)}, Keywords:""}
2018/08/07 07:00:49 MTP request ANDROID_GET_PARTIAL_OBJECT64 [242846 0 0 131072]
send: 0x1c bytes with ep 0x1:
0000: 1c00 0000 0100 c195 3f00 0000 9eb4 0300  ........?.......
0010: 0000 0000 0000 0000 0000 0200            ............
2018/08/07 07:00:49 fatal error LIBUSB_ERROR_OVERFLOW; closing connection.
2018/08/07 07:00:49 MTP request CloseSession []
send: 0xc bytes with ep 0x1:
0000: 0c00 0000 0100 0310 4000 0000            ........@...
2018/08/07 07:00:59 MTP sendreq failed: LIBUSB_ERROR_TIMEOUT
2018/08/07 07:00:59 USB: Reset, err: <nil>
2018/08/07 07:00:59 USB: ReleaseInterface 0x0, err: <nil>
2018/08/07 07:00:59 USB: Close, err: <nil>
2018/08/07 07:00:59 AndroidGetPartialObject64 failed: LIBUSB_ERROR_OVERFLOW
2018/08/07 07:00:59 AndroidGetPartialObject64 failed: mtp: cannot run operation ANDROID_GET_PARTIAL_OBJECT64, device is not open
2018/08/07 07:00:59 AndroidGetPartialObject64 failed: mtp: cannot run operation ANDROID_GET_PARTIAL_OBJECT64, device is not open

media-libs/libmtp
dev-libs/go-usb
dev-libs/go-fuse

All using upstream sources.

dev-lang/go-1.10.3
kernel 4.9.24
distributions Gentoo Linux

**Comment by raineth** [comment]
Greetings,

I ran into this error as well during mounting.  After some digging, this is what I've found (tl;dr: bump packetSize from 512 to 1024):

This error occurs because USB 3 increased the maximum bulk transfer size to 1024 bytes, but in [mtp/mtp.go:220](https://github.com/hanwen/go-mtpfs/blob/master/mtp/mtp.go#L220) the maximum packet size is set at 512 bytes (the USB 2 maximum).  Modern devices (e.g. the Galaxy S8 I encountered this with) are using those larger packet sizes and libusb rightfully rejects the response with `LIBUSB_ERROR_OVERFLOW`.

I set packetSize to 1024, rebuilt, and everything works again.

It seems like it would be more correct to fetch the maximum packet size from the endpoint descriptor, although I don't know Go very well so maybe that's painful for some reason.

For additional context, here's the MTP USB descriptor for my device (Samsung Galaxy S8, samsung/dreamqlteue/dreamqlteue:8.0.0/R16NW/G950U1UEU5CRJ2:user/release-keys) and the 571-byte GetDeviceInfo response that triggered the error:

Descriptor:
```
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass         6 Imaging
      bInterfaceSubClass      1 Still Image Capture
      bInterfaceProtocol      1 Picture Transfer Protocol (PIMA 15470)
      iInterface              5 MTP
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               4
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0400  1x 1024 bytes
        bInterval               0
        bMaxBurst               4
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x001c  1x 28 bytes
        bInterval               6
        bMaxBurst               0
        INTERFACE CLASS:  08 24 80 0c 00 01 00 01
```

Debug output for GetDeviceInfo that was >512 bytes and caused the error for me:
```
2018/11/22 00:32:19 MTP request GetDeviceInfo []
send: 0xc bytes with ep 0x1:
0000: 0c00 0000 0100 0110 0400 0000            ............
recv: 0x23b bytes with ep 0x81:
0000: 3b02 0000 0200 0110 0400 0000 6400 0600  ;...........d...
0010: 0000 6400 7a6d 0069 0063 0072 006f 0073  ..d.zm.i.c.r.o.s
0020: 006f 0066 0074 002e 0063 006f 006d 003a  .o.f.t...c.o.m.:
0030: 0020 0031 002e 0030 003b 0020 006d 0069  . .1...0.;. .m.i
0040: 0063 0072 006f 0073 006f 0066 0074 002e  .c.r.o.s.o.f.t..
0050: 0063 006f 006d 002f 0057 004d 0050 0050  .c.o.m./.W.M.P.P
0060: 0044 003a 0020 0031 0031 002e 0030 003b  .D.:. .1.1...0.;
0070: 0020 006d 0069 0063 0072 006f 0073 006f  . .m.i.c.r.o.s.o
0080: 0066 0074 002e 0063 006f 006d 002f 0057  .f.t...c.o.m./.W
0090: 004d 0050 0050 0044 003a 0020 0031 0030  .M.P.P.D.:. .1.0
00a0: 002e 0030 003b 0073 0061 006d 0073 0075  ...0.;.s.a.m.s.u
00b0: 006e 0067 002e 0063 006f 006d 002f 006b  .n.g...c.o.m./.k
00c0: 0069 0065 0073 003a 0034 002e 0031 003b  .i.e.s.:.4...1.;
00d0: 0073 0061 006d 0073 0075 006e 0067 002e  .s.a.m.s.u.n.g..
00e0: 0063 006f 006d 002f 0064 0065 0076 0069  .c.o.m./.d.e.v.i
00f0: 0063 0065 0073 0074 0061 0074 0075 0073  .c.e.s.t.a.t.u.s
0100: 003a 0030 003b 0000 0000 0026 0000 0001  .:.0.;.....&....
0110: 1002 1003 1004 1005 1006 1007 1008 1009  ................
0120: 100b 100c 100d 1014 1015 1016 101b 1010  ................
0130: 9811 9802 9801 9803 9804 9805 9806 9801  ................
0140: 9202 920a 1011 1012 1017 1019 101a 1007  ................
0150: 9808 9801 9502 9503 9504 9505 0000 0002  ................
0160: 4003 4004 4005 400c 4006 0000 0001 5001  @.@.@.@.@.....P.
0170: d402 d404 d407 d405 d400 0000 0017 0000  ................
0180: 0084 b985 b909 3001 b981 b901 3801 3005  ......0.....8.0.
0190: ba00 3006 b908 b907 3804 380b 380a 300b  ..0.....8.8.8.0.
01a0: 300c 3082 b900 3880 b910 ba11 ba03 ba1e  0.0...8.........
01b0: 5300 6100 6d00 7300 7500 6e00 6700 2000  S.a.m.s.u.n.g. .
01c0: 4500 6c00 6500 6300 7400 7200 6f00 6e00  E.l.e.c.t.r.o.n.
01d0: 6900 6300 7300 2000 4300 6f00 2e00 2c00  i.c.s. .C.o...,.
01e0: 2000 4c00 7400 6400 2e00 0000 0a53 004d   .L.t.d......S.M
01f0: 002d 0047 0039 0035 0030 0055 0031 0000  .-.G.9.5.0.U.1..
0200: 000f 4700 3900 3500 3000 5500 3100 5500  ..G.9.5.0.U.1.U.
0210: 4500 5500 3500 4300 5200 4a00 3200 0000  E.U.5.C.R.J.2...
0220: 0c3c 0072 0065 0064 0061 0063 0074 0065  .<.r.e.d.a.c.t.e
0230: 0064 0021 003e 0000 0000 00              .d.!.>.....
2018/11/22 00:32:19 MTP data 0x23b bytes
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 0400 0000            ....... ....
2018/11/22 00:32:19 MTP response OK []
2018/11/22 00:32:19 MTP decoded &mtp.DeviceInfo{StandardVersion:0x64, MTPVendorExtensionID:0x6, MTPVersion:0x64, MTPExtension:"microsoft.com: 1.0; microsoft.com/WMPPD: 11.0; microsoft.com/WMPPD: 10.0;samsung.com/kies:4.1;samsung.com/devicestatus:0;", FunctionalMode:0x0, OperationsSupported:[]uint16{0x1001, 0x1002, 0x1003, 0x1004, 0x1005, 0x1006, 0x1007, 0x1008, 0x1009, 0x100b, 0x100c, 0x100d, 0x1014, 0x1015, 0x1016, 0x101b, 0x9810, 0x9811, 0x9802, 0x9801, 0x9803, 0x9804, 0x9805, 0x9806, 0x9201, 0x9202, 0x100a, 0x1011, 0x1012, 0x1017, 0x1019, 0x101a, 0x9807, 0x9808, 0x9501, 0x9502, 0x9503, 0x9504}, EventsSupported:[]uint16{0x4002, 0x4003, 0x4004, 0x4005, 0x400c}, DevicePropertiesSupported:[]uint16{0x5001, 0xd401, 0xd402, 0xd404, 0xd407, 0xd405}, CaptureFormats:[]uint16{}, PlaybackFormats:[]uint16{0xb984, 0xb985, 0x3009, 0xb901, 0xb981, 0x3801, 0x3001, 0xba05, 0x3000, 0xb906, 0xb908, 0x3807, 0x3804, 0x380b, 0x300a, 0x300b, 0x300c, 0xb982, 0x3800, 0xb980, 0xba10, 0xba11, 0xba03}, Manufacturer:"Samsung Electronics Co., Ltd.", Model:"SM-G950U1", DeviceVersion:"G950U1UEU5CRJ2", SerialNumber:"<redacted!>"}
```

Cheers!

**Comment by eqvinox** [comment]
same issue & same fix here (Sony XZ2 Compact), just changing
```
./mtp/mtp.go:const packetSize = 1024
```
fixes the problem

**Comment by hanwen** [comment]
sorry for the delay here. I rarely work on go-mtpfs these days.
 
in commit 14927b3, I made it use the maxpacketsize as packet size. Hopefully this fixes things.
