### ISSUE TITLE
src/github.com/hanwen/go-mtpfs/main.go:68:11: undefined: fuse.NewLockingRawFileSystem

### ISSUE THREAD

**Issue by nsajko** [hanwen/go-mtpfs#135]
The build of go-mtpfs fails because of the stated error. The cause is that the API was removed from go-fuse in https://github.com/hanwen/go-fuse/commit/bffc1113aba2c80453f8d7d9b62bc1895123a557

**Comment by hanwen** [comment]
does commit cc0483c fix things for you?

**Comment by nsajko** [comment]
Yes.
