### ISSUE TITLE
cannot find package "github.com/hanwen/go-fuse/v2/fs"

### ISSUE THREAD

**Issue by ihbing** [hanwen/go-mtpfs#141]
`/golang$ go get github.com/hanwen/go-mtpfs
package github.com/hanwen/go-mtpfs
	imports context: unrecognized import path "context"
package github.com/hanwen/go-mtpfs
	imports github.com/hanwen/go-fuse/v2/fs
	imports github.com/hanwen/go-fuse/v2/fs
	imports github.com/hanwen/go-fuse/v2/fs: cannot find package "github.com/hanwen/go-fuse/v2/fs" in any of:
	/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/v2/fs (from $GOROOT)
	/tmp/go/src/github.com/hanwen/go-fuse/v2/fs (from $GOPATH)
package github.com/hanwen/go-mtpfs
	imports github.com/hanwen/go-fuse/v2/fs
	imports github.com/hanwen/go-fuse/v2/fuse
	imports github.com/hanwen/go-fuse/v2/fuse
	imports github.com/hanwen/go-fuse/v2/fuse: cannot find package "github.com/hanwen/go-fuse/v2/fuse" in any of:
	/usr/lib/go/src/pkg/github.com/hanwen/go-fuse/v2/fuse (from $GOROOT)
	/tmp/go/src/github.com/hanwen/go-fuse/v2/fuse (from $GOPATH)
`

**Comment by ihbing** [comment]
Didn't find the code for v2 in your repository, you didn't upload it?

**Comment by jamespharvey20** [comment]
Is this attempting to be one of the `v2` tags?  Or a release that's unmarked?  As @ihbing said, there's no directory in the `go-fuse` repo of `v2/fuse`, so this fails:

````
$ go get github.com/hanwen/go-mtpfs
package github.com/hanwen/go-fuse/v2/fs: cannot find package "github.com/hanwen/go-fuse/v2/fs" in any of:
        /usr/lib/go/src/github.com/hanwen/go-fuse/v2/fs (from $GOROOT)
        /tmp/go/src/github.com/hanwen/go-fuse/v2/fs (from $GOPATH)
package github.com/hanwen/go-fuse/v2/fuse: cannot find package "github.com/hanwen/go-fuse/v2/fuse" in any of:
        /usr/lib/go/src/github.com/hanwen/go-fuse/v2/fuse (from $GOROOT)
        /tmp/go/src/github.com/hanwen/go-fuse/v2/fuse (from $GOPATH)
````

**Comment by hanwen** [comment]
I forgot to check in the modules configuration. Fixed in https://github.com/hanwen/go-mtpfs/commit/05f80d1b888f5a0ef34a87f18bdfd93e919f49ca
