### ISSUE TITLE
the directory containing `libusb-1.0.pc'

### ISSUE THREAD

**Issue by ihbing** [hanwen/go-mtpfs#142]
`# D:\project\go\bin\pkg-config.exe --cflags  -- libusb-1.0
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found`

**Comment by hanwen** [comment]
it looks like you are trying to use go-mtpfs on windows. This will never work.

libusb-1.0.pc is usually contained in the libusb development package, eg. libusb-1.0-0-dev on Ubuntu.
