### ISSUE TITLE
Not able to list the devices.

### ISSUE THREAD

**Issue by ganeshrvel** [hanwen/go-mtpfs#150]
I am using macOS and I am trying to write code to access my android phone.

I installed pkg-config and libusb via homebrew

My code:

```dart
package main

import "github.com/hanwen/go-mtpfs/mtp"
import "github.com/hanwen/usb"

func main() {
	usbContext := usb.NewContext()

	device, err := mtp.FindDevices(usbContext)

	println("error: ", err)

	if err != nil {
		println(device)
	}
}

```

it outputs: error: (0x0,0x0)

What am I doing wrong here? I am trying to write a portable mtp application using go-mtpfs.

**Comment by hanwen** [comment]
https://play.golang.org/p/Qcx2Age8kfH - (0x0,0x0) means that the error is nil, ie. there is no error.

It looks like you have little experience writing Go. I recommend learning the language fully first.

**Comment by ganeshrvel** [comment]
@hanwen hey, I am yeah still trying to figure out golang. I am sure that I can pick it up.

I am trying to write an app to access the MTP devices. There isn't much code samples out there. Are there any resources or codes that I could use to understand how to get some basic things done?


Like list MTP devices, select a device, get storage, copy files etc.. ?

It had be a great help.

Thanks

**Comment by hanwen** [comment]
once you are fluent and understand Go, you could look at the source code of go-mtpfs. I'm not sure if it works on OSX, though.

**Comment by ganeshrvel** [comment]
Oho, is there any go-mtpfs port for macos? Is there a reason why it's still not supported? 

I am actually looking a replacement for libmtp and thought that go-mtpfs could help

**Comment by hanwen** [comment]
i've heard of people using it on osx, but I don't have a mac myself, so I can't vouch for it.
