### ISSUE TITLE
LIBUSB_ERROR_TIMEOUT on Samsung Galaxy Note 2

### ISSUE THREAD

**Issue by zeitkunst** [hanwen/go-mtpfs#33]
I followed the conversation on the recently-closed bug for Samsung devices (https://github.com/hanwen/go-mtpfs/issues/29), but unfortunately I am still hit by the LIBUSB_ERROR_TIMEOUT bug. I'm on Debian Wheezy.

I'm on the latest revision of go-mtpfs, I believe:

```nknouf@nomadicsounds go-mtpfs> git rev-parse HEAD
731851c9363ffa26206219b9fbec1897f0b3d9d1```

The debug logs don't provide much info for me:

```
nknouf@nomadicsounds go-mtpfs> ../../../../bin/go-mtpfs -debug=usb,mtp -usb-timeout=10000 /media/noteII
2013/03/24 10:28:49 MTP request OpenSession [1101278637]
2013/03/24 10:28:59 MTP sendreq failed: LIBUSB_ERROR_TIMEOUT
2013/03/24 10:28:59 OpenSession failed: LIBUSB_ERROR_TIMEOUT; attempting reset
2013/03/24 10:28:59 USB: ReleaseInterface 0x0, err: <nil>
2013/03/24 10:28:59 USB: Close, err: <nil>
2013/03/24 10:29:00 USB: Open, err: <nil>
2013/03/24 10:29:00 USB: ClaimInterface 0x0, err: <nil>
2013/03/24 10:29:00 MTP request OpenSession [1267048825]
2013/03/24 10:29:10 MTP sendreq failed: LIBUSB_ERROR_TIMEOUT
2013/03/24 10:29:10 Configure failed: OpenSession after reset: LIBUSB_ERROR_TIMEOUT
nknouf@nomadicsounds go-mtpfs>
```

Any suggestions of what else to try?

**Comment by likewhoa** [comment]
Running into similar issue with my Nexus 6 phone. I will update issue with debug output on my end tomorrow. so far I am running both go-{mtpfs,fuse} from HEAD as of this posting. It seems this issue is not just for Samsung devices only.

**Comment by hanwen** [comment]
@likewhoa - can you open a separate issue? Samsung uses a different MTP stack, so typically exhibits separate problems.

**Comment by likewhoa** [comment]
@hanwen sure, I will this morning.
