### ISSUE TITLE
wrong timestamp, outdated files & failing moves

### ISSUE THREAD

**Issue by g2flyer** [hanwen/go-mtpfs#51]
I try to synchronize some files via unison from linux (ubuntu 13.10) to a nexus 5 (android 4.4) and nook (android 4.1).  
On the nook the file-changes didn't seem to get properly reflected by go-mtpfs but from what i read this was related to the media-scanner not doing its job properly (note in this case all changes where triggered by mtpfs, nothing via adb shell or other android apps!) and running SDrescan or alike inside nook, while slow, did seem to handle that problem.

However, on android 4.4 i run into additional problems: 
- apps like SDrescan do not seem to work anymore with android 4.4; 
- I also noticed that after unmount and remount the timestamps of the files were off by 8 years while they were correct before the unmount. Note that i am on both devices on PST8PDT but interestingly the wrong timestamps are 8 hours _earlier_ not later. I also played with env TZ= when running go-mtpfs but that didn't make any difference. Seems somewhere the timezone conversion/normalization is wrong
- lastly, while rename seems to work with the nook, i get errors when unison tries to rename tmpfiles (e.g., `Error in renaming /media/msteiner/nexus/Internal storage/babbage/mobileorg/.unison.checksums.dat.2fb7c5faf78fda0a030b6e431510b8a3.unison.tmp to /media/msteiner/nexus/Internal storage/babbage/mobileorg/checksums.dat:
  Input/output error [rename(/media/msteiner/nexus/Internal storage/babbage/mobileorg/.unison.checksums.dat.2fb7c5faf78fda0a030b6e431510b8a3.unison.tmp)]". When i try manually it also fails, e.g.,`mv -f /media/msteiner/nexus/Internal\ storage/babbage/mobileorg/.unison.checksums.dat.2fb7c5faf78fda0a030b6e431510b8a3.unison.tmp /media/msteiner/nexus/Internal\ storage/babbage/mobileorg/checksums.dat
  mv: cannot move ‘/media/msteiner/nexus/Internal storage/babbage/mobileorg/.unison.checksums.dat.2fb7c5faf78fda0a030b6e431510b8a3.unison.tmp’ to ‘/media/msteiner/nexus/Internal storage/babbage/mobileorg/checksums.dat’: Input/output error''.  However, mv does work for other files i create.

It seems there are problems in mtpfs implementation/media-scanner inside android, so i'm not sure whether the problems are in android or go-mtpfs but i thought i report them anyway, maybe you (or somebody else) can shed some light in the problem.

thanks for help (as well as providing go-mtpfs: despite these problems it is still much better than the standard linux  mtpfs implementation)!

**Comment by JanisE** [comment]
I've encountered the incorrect handling of the timezone, too. My locale time currently is GMT+03:00. When I copy (`$ nemo --version: nemo 2.2.4`) a file from a go-mtpfs-mounted folder, the copy gets a modification time 3 hours later than that of the original file.

**Comment by hanwen** [comment]
closing due to age.
