### ISSUE TITLE
selectStorages failed: EOF

### ISSUE THREAD

**Issue by digulla** [hanwen/go-mtpfs#59]
When I start go-mtpfs on Ubuntu 13.04, I get this output:

```
> ./bin/go-mtpfs -debug "usb,data,mtp,fuse" ~/mnt
2014/03/06 09:02:31 MTP request OpenSession [778784311]
send: 0x10 bytes with ep 0x1:
0000: 1000 0000 0100 0210 0000 0000 374e 6b2e  ............7Nk.
recv: 0xc bytes with ep 0x82:
0000: 0c00 0000 0300 0120 0000 0000            ....... ....
2014/03/06 09:02:31 MTP response OK []
2014/03/06 09:02:31 MTP request GetStorageIDs []
send: 0xc bytes with ep 0x1:
0000: 0c00 0000 0100 0410 0100 0000            ............
recv: 0xc bytes with ep 0x82:
0000: 0c00 0000 0300 0120 0100 0000            ....... ....
2014/03/06 09:02:31 MTP response OK []
2014/03/06 09:02:31 selectStorages failed: EOF
> ls
```

The same is true when I run the tests for commit 839c126fe2aeec771fb8c936e6fd0b6a5109d7fc:

```
> bash ./all.bash 
+ for x in fs mtp
+ go build github.com/hanwen/go-mtpfs/fs
+ go test -i github.com/hanwen/go-mtpfs/fs
+ go test github.com/hanwen/go-mtpfs/fs
--- FAIL: TestReadBlockBoundaryAndroid (0.01 seconds)
        device_test.go:49: selectStorages failed: EOF
--- FAIL: TestReadBlockBoundaryNormal (0.01 seconds)
        device_test.go:49: selectStorages failed: EOF
--- FAIL: TestAndroid (0.01 seconds)
        device_test.go:49: selectStorages failed: EOF
--- FAIL: TestNormal (0.01 seconds)
        device_test.go:49: selectStorages failed: EOF
FAIL
FAIL    github.com/hanwen/go-mtpfs/fs   0.063s
```

**Comment by mpnolan** [comment]
I'm seeing this error with my Galaxy S5 / Android 6.0.1 now. Since it used to work, I suspect it changed with an Android update.

I do see an Allow/Deny popup right after the EOF error: "An MTP connection will be established to access the data on the connected device: Allow/Deny" Even though I select Allow it continues to fail. Any ideas?

**Comment by ninrod** [comment]
Just hit this.

**Comment by gahisee** [comment]
similar results on Galaxy S8+

go-mtpfs -debug "usb,data,mtp,fuse" /mnt/mtp
2019/09/09 08:19:39 MTP request OpenSession [1800024239]
send: 0x10 bytes with ep 0x1:
0000: 1000 0000 0100 0210 0000 0000 af30 4a6b  .............0Jk
2019/09/09 08:19:39 MTP sendreq failed: LIBUSB_ERROR_IO
2019/09/09 08:19:39 OpenSession failed: LIBUSB_ERROR_IO; attempting reset
2019/09/09 08:19:39 USB: Close, err: <nil>
2019/09/09 08:19:40 USB: Open, err: <nil>
2019/09/09 08:19:40 USB: ClaimInterface 0x0, err: <nil>
2019/09/09 08:19:40 MTP request OpenSession [1503821495]
send: 0x10 bytes with ep 0x1:
0000: 1000 0000 0100 0210 0000 0000 b77e a259  .............~.Y
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 0000 0000            ....... ....
2019/09/09 08:19:40 MTP response OK []
2019/09/09 08:19:40 MTP request GetStorageIDs []
send: 0xc bytes with ep 0x1:
0000: 0c00 0000 0100 0410 0100 0000            ............
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 0100 0000            ....... ....
2019/09/09 08:19:40 MTP response OK []
2019/09/09 08:19:40 selectStorages failed: EOF

NOTE:  Dolphin has no problems showing Phone folders
=====   despite the fact /mnt/mtp is not mounted.
             Since it has worked before, I'm suspecting S8+ and its latest update.

**Comment by hanwen** [comment]
closing due to age.

**Comment by crabdancing** [comment]
Bug still exists in 2024. :/

```
go-mtpfs -debug "usb,data,mtp,fuse" -android=0 ~/mnt
2024/01/25 00:41:30 MTP request OpenSession [1258279721]
send: 0x10 bytes with ep 0x1:
0000: 1000 0000 0100 0210 0000 0000 29d3 ff4a  ............)..J
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 0000 0000            ....... ....
2024/01/25 00:41:30 MTP response OK []
2024/01/25 00:41:30 MTP request GetStorageIDs []
send: 0xc bytes with ep 0x1:
0000: 0c00 0000 0100 0410 0100 0000            ............
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0120 0100 0000            ....... ....
2024/01/25 00:41:30 MTP response OK []
2024/01/25 00:41:30 selectStorages failed: EOF
```

Target is a Samsung Galaxy 6 tablet. No other error messages.
