### ISSUE TITLE
Droid Maxx stopped working LIBUSB_ERROR_TIMEOUT

### ISSUE THREAD

**Issue by sbrown44** [hanwen/go-mtpfs#66]
Hi, I installed go-mtpfs and everything was working until I tried again to use it yesterday. Tried a variety of cables and ports. 
When it starts, it says FUSE mounted, and it creates  folder called Internal Storage under the mount point, but trying to ls anything in there results in "fatal error LIBUSB_ERROR_TIMEOUT; closing connection." after about 10 seconds and many messages after like "GetObjectInfo for handle 24413 failed: mtp: cannot run operation GetObjectInfo, device is not open"

The device is a droid maxx Android 4.4. Can you help ?

**Comment by hanwen** [comment]
closing due to age.
