### ISSUE TITLE
Linux does not recognize mounted partition

### ISSUE THREAD

**Issue by yuripaes** [hanwen/go-mtpfs#69]
Hi,

I compiled go-mtpfs with success after upgrading to golang 1.3 and libmtp 1.1.5.

   > go version go1.3 linux/amd64
   > libmtp version: 1.1.5

I'm using Scientific Linux release 6.5 (Carbon) [2.6.32-431.20.3.el6.x86_64] and trying to connect a Samsung Galaxy SII GT-I9100.

Although, I see no errors when running go-mtpfs, it appears that the mounting point filesystem is not recognized by linux. The output of ls shows the following:

   d??????????  ? ?         ?                ?            ? MyAndroid

After I unmount it (fusermount -u...), it is displayed fine.

   drwxrwxr-x   2 yuri.paes yuri.paes     4096 Jul  6 09:05 MyAndroid

- Follows the mtp-detect output: http://pastebin.com/dqRtLqTx
- Follows the go-mtpfs -debug "usb,data,mtp,fuse": http://pastebin.com/w82Q1uKR

If any other information is needed, please let me know.

Thanks in advance!

**Comment by hanwen** [comment]
usually there will be a GetAttr in the log that is triggered by doing "ls -l MyAndroid/". Was it there?
