### ISSUE TITLE
Some directories show no content

### ISSUE THREAD

**Issue by pebbe** [hanwen/go-mtpfs#70]
When I look on my phone in /storage/emulated/0/.semc-fullbackup I see a subdirectory 2014-09-27-024013 that I want to copy to linux. But viewed from Linux, the directory .semc-fullbackup shows no subdirectory.

go version go1.3.2 linux/amd64
phone: Sony Xperia Z1

**Comment by hanwen** [comment]
it's possible that the phone's media DB is out of sync with the filesystem on the device.
