### ISSUE TITLE
Doesn't read files on Nexus 4

### ISSUE THREAD

**Issue by alseambusher** [hanwen/go-mtpfs#73]
go-mtpfs <folder>
2014/11/06 15:03:50 FUSE mounted
2014/11/06 15:04:01 writer: Write/Writev failed, err: 22=invalid argument. opcode: READDIR
2014/11/06 15:04:01 writer: Write/Writev failed, err: 22=invalid argument. opcode: READDIR

I get the above error when I try to access "Internal Storage" folder in mount point .

**Comment by hanwen** [comment]
closing due to age.
