### ISSUE TITLE
AndroidBeginEditObject failed: OperationNotSupported with an Xperia Z1 on ArchLinux

### ISSUE THREAD

**Issue by dasois** [hanwen/go-mtpfs#80]
I am trying to send a large file to an xperia z1 using go-mtpfs on archlinux.
After trying to copy the file I get: AndroidBeginEditObject failed: OperationNotSupported

**Comment by xkonni** [comment]
just encountered the same issue with the latest git-version on archlinux. your command fixed it, thanks!

**Comment by dasois** [comment]
Thank you, solved it! :)
