### ISSUE TITLE
Missing folders or folders shown as files (Nexus 5, Android 5.0.1)

### ISSUE THREAD

**Issue by kynan** [hanwen/go-mtpfs#83]
go-mtpfs dd03f8c
Device: Nexus 5, Android 5.0.1

I can only mount storage via go-mtpfs if not auto mounted via gvfs.

Some folders however are missing and others are recognized as files of 4k size.

The errors I see are as follows:
```
$ go-mtpfs /media/MyAndroid/                                                                                                                                   
2015/01/15 08:28:18 FUSE mounted
2015/01/15 08:28:28 AndroidGetPartialObject64 failed: GeneralError
...
```
Mounting without Android extensions shows the same symptoms with a different error:
```
$ go-mtpfs -android=false /media/MyAndroid/
2015/01/15 08:42:16 FUSE mounted
2015/01/15 08:42:26 fetched ".enref", 7 bytes in 2 ms. 0.0 MB/s
2015/01/15 08:42:26 fetched ".profig.os", 36 bytes in 2 ms. 0.0 MB/s
2015/01/15 08:42:26 error fetching: GeneralError
2015/01/15 08:42:26 fetch failed: input/output error
...
```

Happy to provide any other diagnostics if that helps.

**Comment by hanwen** [comment]
gvfs also gives errors, right?

you could try to see if something shows up on the device logs, with adb logcat (see http://developer.android.com/tools/help/logcat.html ).

there is logging code on the android side. Unfortunately, it requires recompiling Android, so it's very practical.

**Comment by kynan** [comment]
I can't test right now, but afair I couldn't access storage at all through gvfs i.e. the mount point was empty (on Linux Mint 17 i.e. Ubunutu 14.04). Will have a got with logcat tonight.

**Comment by kynan** [comment]
@hanwen I tried to gather some logcat output, but couldn't make any sense of it so far. In particular it seems that `adb` crashes whenever I mount the fs with `go-mtpfs`. Are there any keywords in the logcat output to grep for that might give an indication?

Also I verified that the view of the MTP fs I get from gvfs is the *same* as the one I get from `go-mtpfs` i.e. the same folders are not recognized.

**Comment by kynan** [comment]
Grepping from `MTP` in the logcat output I only get the following (repeatedly):
```
D/MtpService(29307): starting MTP server in MTP mode
D/MtpService(29307): addStorageLocked 65537 /storage/emulated/0
D/MtpService(29307): updating state; isCurrentUser=true, mMtpLocked=false
```

**Comment by hanwen** [comment]
Sorry for the delay. Yeah, the device logs don't say much. One option is to
clear the cached data of the Media process (settings > apps). This blows
away the database that the MTP process uses. It is then rebuilt, which
hopefully restores things back to normal. If you attempt this, do make sure
you have a copy of any important files you might have stored on the device.

**Comment by kynan** [comment]
Thanks, I'll try that next time. My workaround was copying "inaccessible" files to Google Drive from the device.
