### ISSUE TITLE
Instructions in the readme do not work for Ubuntu 14.10 (libusb1-devel)

### ISSUE THREAD

**Issue by dnadales** [hanwen/go-mtpfs#84]
The package is not found by apt-get.

**Comment by hanwen** [comment]
try this : sudo apt-get install libusb-1.0-0-dev

**Comment by capitanbatata** [comment]
Indeed. I installed that library. Shouldn't the instructions be updated?

**Comment by kiok46** [comment]
Please update the instructions.

**Comment by JanisE** [comment]
Thanks!

**Comment by hanwen** [comment]
updated README
