### ISSUE TITLE
sync.Pool undefined

### ISSUE THREAD

**Issue by erw1988** [hanwen/go-mtpfs#86]
I'm trying to get the files from the repository, but it keeps spitting out the following at me:

go get github.com/hanwen/go-mtpfs
# github.com/hanwen/go-fuse/fuse
/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:44: undefined: sync.Pool
/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:47: undefined: sync.Pool

Any help? Thanks.

**Comment by hanwen** [comment]
Upgrade to go1.4
