### ISSUE TITLE
Sony Xperia Z1 - ANDROID_GET_PARTIAL_OBJECT64 OperationNotSupported

### ISSUE THREAD

**Issue by gdm85** [hanwen/go-mtpfs#93]
Hi there,

as I understand this problem might be in libmtp.

Phone model is Sony Z1 Xperia (C6903) and Android 4.4.2, kernel is 3.4.0.

When trying to open JPEG images (and others), I see these errors and pictures cannot be opened. Trying to copy such files leads to same errors.
```
2015/05/02 10:23:49 MTP request ANDROID_GET_PARTIAL_OBJECT64 [13869 0 0 131072]
send: 0x1c bytes with ep 0x1:
0000: 1c00 0000 0100 c195 c900 0000 2d36 0000  ............-6..
0010: 0000 0000 0000 0000 0000 0200            ............
recv: 0xc bytes with ep 0x81:
0000: 0c00 0000 0300 0520 c900 0000            ....... ....
2015/05/02 10:23:49 MTP response OperationNotSupported []
```

Perhaps there could be a fallback and not trying to use GetPartialObject if not available on device?

**Comment by hanwen** [comment]
does it work correctly with -android=false ?

**Comment by gdm85** [comment]
@hanwen in that case yes, it works correctly

**Comment by hanwen** [comment]
Can you add the dump when you run with -debug=mtp -android=true?

**Comment by gdm85** [comment]
@hanwen here you go: https://gist.github.com/gdm85/20631bdae15f78ab3a49

**Comment by gdm85** [comment]
Please note that this is not a stock ROM, although it's a modified ROM that uses exactly the official stock one as basis (it's a stripped down version).

**Comment by hanwen** [comment]
Your dump claims the device supports "android.com" extensions, and opcode 95c1 (which is get_partial_object64). There is not much we can do if the device is lying. 

015/05/12 10:33:03 MTP decoded &mtp.DeviceInfo{StandardVersion:0x64, MTPVendorExtensionID:0x6, MTPVersion:0x64, MTPExtension:"microsoft.com: 1.0; android.com: 1.0; microsoft.com/WPDNA: 1.0;sonyericsson.com/SE: 1.0; sony.net/MRLN: 1.0;microsoft.com/DeviceServices:1.0;", FunctionalMode:0x0, OperationsSupported:[]uint16{0x1001, 0x1002, 0x1003, 0x1004, 0x1005, 0x1006, 0x1007, 0x1008, 0x1009, 0x100a, 0x100b, 0x100c, 0x100d, 0x1014, 0x1015, 0x1016, 0x1017, 0x101b, 0x9801, 0x9802, 0x9803, 0x9804, 0x9805, 0x9806, 0x9808, 0x9810, 0x9811, 0x95c1, 0x95c2, 0x95c3, 0x95c4, 0x95c5, 0x9301, 0x9302, 0x9303, 0x9304, 0x9305, 0x9306, 0x9307, 0x9308, 0x9309, 0x930a, 0x9185, 0x9186, 0x9187, 0x9188, 0x9189, 0x9191, 0x9194, 0x9196, 0x9197, 0x940c, 0x940d, 0x9407, 0x9408, 0x9409}, EventsSupported:[]uint16{0x4002, 0x4003, 0x4004, 0x4005, 0xc350, 0xc35a}, DevicePropertiesSupported:[]uint16{0xd401, 0xd402, 0xd405, 0x5003, 0xd120, 0x5001, 0xd302, 0xd303}, CaptureFormats:[]uint16{}, PlaybackFormats:[]uint16{0x3000, 0x300a, 0x3001, 0x3004, 0x3005, 0x3008, 0x3009, 0x3801, 0x3802, 0x3804, 0x3807, 0x3808, 0x380b, 0x380d, 0xb902, 0xb903, 0xb982, 0xb984, 0xba03, 0xba05, 0xba10, 0xba11, 0xba14, 0xba82, 0xb906, 0xb102}, Manufacturer:"Sony", Model:"C6903", DeviceVersion:"1.0", SerialNumber:"BH906F4M13"}
