### ISSUE TITLE
Particular characters in filename such as ':' causes a runtime error after file/folder copy/creation.

### ISSUE THREAD

**Issue by FluidicTapestry** [hanwen/go-mtpfs#95]
I have mounted my Android phone using go-mtpfs (at ~/Android for clarity). I can transfer files and create folders with alphanumeric names no problem.

But if I execute:

mkdir ~/Android/SD\ card/Music/test\\:this

then go-mtpfs dies with a lengthy error log which I will post below because of the colon in the folder name. However, the directory was created, suggesting that the fault does not lie with Android's filesystem. If I remount and create directories within "test:this/", go-mtpfs dies again (and again the directory was created). The same crash occurs with files as well as folders.

abc@abcxyz:~$ go-mtpfs ~/Android
2015/06/29 11:36:18 FUSE mounted
panic: runtime error: index out of range

goroutine 23 [running]:
runtime.panic(0x5c16c0, 0x91907c)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/hanwen/go-mtpfs/mtp.(*Device).SendObjectInfo(0xc208046180, 0xbf2f00020001, 0xc208072900, 0x0, 0x7f5e00000000, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-mtpfs/mtp/ops.go:194 +0x1e9
github.com/hanwen/go-mtpfs/fs.(*folderNode).Mkdir(0xc208026540, 0xc208039710, 0x9, 0x1fd, 0xc20803aaa0, 0xc208025d08, 0x7f5ea2dfbdf0)
	/tmp/go/src/github.com/hanwen/go-mtpfs/fs/fs.go:456 +0x14e
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Mkdir(0xc208025890, 0xc20803aa88, 0xc208039710, 0x9, 0xc20803a9f8, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:260 +0x9a
github.com/hanwen/go-fuse/fuse.(*lockingRawFileSystem).Mkdir(0xc20800e880, 0xc20803aa88, 0xc208039710, 0x9, 0xc20803a9f8, 0xc200000000)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/lockingfs.go:75 +0x9c
github.com/hanwen/go-fuse/fuse.doMkdir(0xc20807e100, 0xc20803a900)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:269 +0x8d
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc20807e100, 0xc20803a900)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:357 +0x242
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20807e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:336 +0xc5
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0xc208039288)
	/usr/lib/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20800e9e0)
	/usr/lib/go/src/pkg/sync/waitgroup.go:129 +0x14b
main.main()
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:88 +0xfbb

goroutine 19 [finalizer wait]:
runtime.park(0x415e50, 0x929e58, 0x91b329)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x929e58, 0x91b329)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [semacquire]:
sync.runtime_Semacquire(0xc2080382a4)
	/usr/lib/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20807e1e0)
	/usr/lib/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/hanwen/go-fuse/fuse.(*Server).Serve(0xc20807e100)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:306 +0x73
main.func·001()
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:83 +0x32
created by main.main
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:85 +0xf46

goroutine 22 [syscall]:
syscall.Syscall(0x0, 0xe, 0xc20808e000, 0x11000, 0x0, 0x45b105, 0xc208078640)
	/usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xe, 0xc20808e000, 0x11000, 0x11000, 0x5b0bc0, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0xe, 0xc20808e000, 0x11000, 0x11000, 0x1, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
github.com/hanwen/go-fuse/fuse.func·040(0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:237 +0x69
github.com/hanwen/go-fuse/fuse.handleEINTR(0x7f5ea2dfdf08, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:212 +0x35
github.com/hanwen/go-fuse/fuse.(*Server).readRequest(0xc20807e100, 0xc20803a201, 0xc20803a240, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:239 +0x21a
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20807e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:317 +0x65
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644

goroutine 24 [syscall]:
syscall.Syscall(0x0, 0xe, 0xc2080c6000, 0x11000, 0x0, 0x45b294, 0xc208025890)
	/usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xe, 0xc2080c6000, 0x11000, 0x11000, 0x5b0bc0, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0xe, 0xc2080c6000, 0x11000, 0x11000, 0x1, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
github.com/hanwen/go-fuse/fuse.func·040(0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:237 +0x69
github.com/hanwen/go-fuse/fuse.handleEINTR(0x7f5ea2df9f08, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:212 +0x35
github.com/hanwen/go-fuse/fuse.(*Server).readRequest(0xc20807e100, 0xc20803ab01, 0xc20803ab40, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:239 +0x21a
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20807e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:317 +0x65
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644
gonzo@gonzo-V5-171:~$ go-mtpfs ~/Android
2015/06/29 11:37:20 FUSE mounted
^[[A^[[A^[[A^[[Bpanic: runtime error: index out of range

goroutine 22 [running]:
runtime.panic(0x5c16c0, 0x91907c)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/hanwen/go-mtpfs/mtp.(*Device).SendObjectInfo(0xc208046180, 0xbf7900020001, 0xc208062b40, 0x0, 0x7f5300000000, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-mtpfs/mtp/ops.go:194 +0x1e9
github.com/hanwen/go-mtpfs/fs.(*folderNode).Mkdir(0xc208026dc0, 0xc2080e81b8, 0x4, 0x1fd, 0xc20803a3e0, 0xc208024778, 0x7f53cfe78df0)
	/tmp/go/src/github.com/hanwen/go-mtpfs/fs/fs.go:456 +0x14e
github.com/hanwen/go-fuse/fuse/nodefs.(*rawBridge).Mkdir(0xc208025890, 0xc20803a3c8, 0xc2080e81b8, 0x4, 0xc20803a338, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/nodefs/fsops.go:260 +0x9a
github.com/hanwen/go-fuse/fuse.(*lockingRawFileSystem).Mkdir(0xc20800e880, 0xc20803a3c8, 0xc2080e81b8, 0x4, 0xc20803a338, 0xc200000000)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/lockingfs.go:75 +0x9c
github.com/hanwen/go-fuse/fuse.doMkdir(0xc20806e100, 0xc20803a240)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:269 +0x8d
github.com/hanwen/go-fuse/fuse.(*Server).handleRequest(0xc20806e100, 0xc20803a240)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:357 +0x242
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20806e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:336 +0xc5
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644

goroutine 16 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc208039278)
	/usr/lib/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20800e9e0)
	/usr/lib/go/src/pkg/sync/waitgroup.go:129 +0x14b
main.main()
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:88 +0xfbb

goroutine 19 [finalizer wait, 6 minutes]:
runtime.park(0x415e50, 0x929e58, 0x91b329)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x929e58, 0x91b329)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 17 [syscall, 6 minutes]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 20 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc208038294)
	/usr/lib/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc20806e1e0)
	/usr/lib/go/src/pkg/sync/waitgroup.go:129 +0x14b
github.com/hanwen/go-fuse/fuse.(*Server).Serve(0xc20806e100)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:306 +0x73
main.func·001()
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:83 +0x32
created by main.main
	/tmp/go/src/github.com/hanwen/go-mtpfs/main.go:85 +0xf46

goroutine 23 [syscall]:
syscall.Syscall(0x0, 0xe, 0xc20808e000, 0x11000, 0x0, 0x45b105, 0xc208068640)
	/usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xe, 0xc20808e000, 0x11000, 0x11000, 0x5b0bc0, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0xe, 0xc20808e000, 0x11000, 0x11000, 0x1, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
github.com/hanwen/go-fuse/fuse.func·040(0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:237 +0x69
github.com/hanwen/go-fuse/fuse.handleEINTR(0x7f53cfe76f08, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:212 +0x35
github.com/hanwen/go-fuse/fuse.(*Server).readRequest(0xc20806e100, 0xc20803a901, 0xc20803a900, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:239 +0x21a
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20806e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:317 +0x65
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644

goroutine 24 [syscall]:
syscall.Syscall(0x0, 0xe, 0xc2080aa000, 0x11000, 0x0, 0x45b294, 0xc208025890)
	/usr/lib/go/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0xe, 0xc2080aa000, 0x11000, 0x11000, 0x5b0bc0, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/zsyscall_linux_amd64.go:838 +0x75
syscall.Read(0xe, 0xc2080aa000, 0x11000, 0x11000, 0x1, 0x0, 0x0)
	/usr/lib/go/src/pkg/syscall/syscall_unix.go:136 +0x5c
github.com/hanwen/go-fuse/fuse.func·040(0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:237 +0x69
github.com/hanwen/go-fuse/fuse.handleEINTR(0x7f53cfe74f08, 0x0, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:212 +0x35
github.com/hanwen/go-fuse/fuse.(*Server).readRequest(0xc20806e100, 0xc20803ab01, 0xc20803ab40, 0x0)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:239 +0x21a
github.com/hanwen/go-fuse/fuse.(*Server).loop(0xc20806e100, 0x1)
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:317 +0x65
created by github.com/hanwen/go-fuse/fuse.(*Server).readRequest
	/tmp/go/src/github.com/hanwen/go-fuse/fuse/server.go:263 +0x644

**Comment by hanwen** [comment]
thanks for the report. I've stopped the crash. 

Curiously, the --vfat option (which defaults to true) should have stopped the ":" from reaching the device. I'll investigate separately.

**Comment by hanwen** [comment]
fixed, too.
