### ISSUE TITLE
Gentoo installation successful but non-functional

### ISSUE THREAD

**Issue by scottfurry** [hanwen/go-mtpfs#96]
I am able to install from gentoo repositories (which pull source from git repo in some instances).
However, once install go-mtpfs will fail to function with the error
"Could not find fusermount binary: exec: "fusermount": executable file not found in $PATH"
fusermount cannot be located on the system.

Have rebuilt dependencies and libraries to with no success.
This worked last week!?

**Comment by scottfurry** [comment]
problem persists.
No change in symptoms.

**Comment by hanwen** [comment]
install the package which provides fusermount. Probably called fuse-tools or something.

**Comment by scottfurry** [comment]
For completeness...
gentoo packaging has a missing dependency.
dev-libs/go-fuse (a dependency of sys-fs/go-mtpfs) is NOT dependent on sys-fs/fuse (installs fusermount).

Installation instructions on gentoo wiki are incomplete.
emerge --ask sys-fs/go-mtpfs sys-fs/fuse
